backend/modules/catalog/models/Property.php
<?php

namespace backend\modules\catalog\models;

use backend\behaviors\PositionBehavior;
use backend\modules\catalog\models\load\PropertyLoad;
use common\models\Lang;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "property".
 *
 * @property integer $id
 * @property string $code
 * @property integer $handle
 * @property integer $updated_at
 * @property integer $created_at
 * @property integer $status
 * @property integer $multiple
 *
 * @property ProductPropery[] $productProperies
 * @property PropertyData[] $propertyDatas
 */
class Property extends \yii\db\ActiveRecord
{
    const STATUS_ACTIVE = 1;
    const STATUS_NOTACTIVE = 0;

    const MULTIPLE_YES = 1;
    const MULTIPLE_NOT = 0;

    const HANDLE_TEXT = 1;
    const BASE_PROPERTY_ID = [1, 6];
    const BASE_NEW_PROPERTY_ID = [1, 3, 6];
    const COLOR_ID = 1;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'property';
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['updated_at', 'created_at', 'status'], 'integer'],
            [['key'], 'string', 'max' => 40],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'code' => 'Code',
            'handle' => 'Обработчик',
            'updated_at' => 'Редактировано',
            'created_at' => 'Создано',
            'status' => 'Статус',
            'multiple' => 'Multiple',
            'title' => 'Название'
        ];
    }

    public function getName()
    {
        return $this->code;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCatalogProperies()
    {
        return $this->hasMany(CatalogPropery::className(), ['property_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPropertyDatas()
    {
        return $this->hasMany(PropertyData::className(), ['property_id' => 'id']);
    }


    public function getStatusList()
    {
        return [
            self::STATUS_ACTIVE => Yii::t('common', 'Активный'),
            self::STATUS_NOTACTIVE => Yii::t('common', 'Неактивный')
        ];
    }

    public function getStatusDetail()
    {
        return isset($this->statusList[$this->status]) ? $this->statusList[$this->status] : '';
    }

    public function getMultipleList()
    {
        return [
            self::MULTIPLE_YES => Yii::t('common', 'Да'),
            self::MULTIPLE_NOT => Yii::t('common', 'Нет')
        ];
    }

    public function getMultipleDetail()
    {
        return isset($this->multipleList[$this->status]) ? $this->multipleList[$this->status] : '';
    }

    public function getLang()
    {
        return $this->hasOne(PropertyLang::className(), ['property_id' => 'id'])->andWhere(['lang_id' => Lang::$current->id]);
    }

    public function getPropertyCategory()
    {
        return $this->hasMany(PropertyCategory::className(), ['property_id' => 'id'])->orderBy('position');
    }

    public function getTitle()
    {
        return $this->lang ? $this->lang->title : '';
    }

    static public function getPropertyAll($map = false)
    {
        $models = self::find()->andWhere(['status' => self::STATUS_ACTIVE])->all();
        if ($map) {
            return ArrayHelper::map($models, 'id', 'title');
        }

        return $models;
    }


}

backend/modules/catalog/controllers/CategoryController.php
<?php

namespace backend\modules\catalog\controllers;

use backend\controllers\BaseController;
use Yii;
use backend\modules\catalog\models\CatalogCategory;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CategoryController implements the CRUD actions for PageCategory model.
 */
class CategoryController extends BaseController
{
    /**
     * Lists all PageCategory models.
     * @return mixed
     */
    public function actionIndex()
    {
        $query = CatalogCategory::find();
        $query->andWhere(['IS', 'parent_id', null]);
        $query->orderBy(['position' => SORT_ASC]);
        $models = $query->all();

        return $this->render('index', [
            'models' => $models,
        ]);
    }

    /**
     * Displays a single PageCategory model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new PageCategory model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new CatalogCategory();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {

            return $this->redirect(['view', 'id' => $model->id]);
        } else {

            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing PageCategory model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing PageCategory model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the PageCategory model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return catalogCategory the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = CatalogCategory::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/modules/catalog/views/category/_form.php
<?php

use backend\widgets\ImperaviWidget;
use backend\widgets\MainInputFile;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use backend\modules\catalog\models\CatalogCategory;
use yii\helpers\ArrayHelper;

$parentsList = CatalogCategory::find()
    ->where(['status' => CatalogCategory::STATUS_ACTIVE])
    ->andFilterWhere(['!=', 'id', $model->id])
    ->orderBy(['position' => SORT_ASC])
    ->all();
?>

<div class="page-category-form">

    <?php $form = ActiveForm::begin(); ?>

<!--    --><?//= $form->field($model, 'title')->widget(ImperaviWidget::className(), [])?>
    <?= $form->field($model, 'title')->textInput(['maxlength' => true])?>

    <?= $form->field($model, 'description')->widget(ImperaviWidget::className(), []) ?>

<!--    --><?//= $form->field($model, 'text')->textarea() ?>

    <div class="row">
        <div class="col-md-4">
            <?= $form->field($model, 'parent_id')
                ->dropDownList(ArrayHelper::map($parentsList, 'id', 'title'), ['prompt' => '']) ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'status')->dropDownList($model::getStatusList()) ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'alias')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'image')->widget(MainInputFile::className(), [
                'language'      => 'ru',
                'path'          => 'catalog',
                'controller'    => '/elfinder', // вставляем название контроллера, по умолчанию равен elfinder
                // фильтр файлов, можно задать массив фильтров https://github.com/Studio-42/elFinder/wiki/Client-configuration-options#wiki-onlyMimes
                'template'      => '<div class="file-input-image"><div class="img">{image}</div> <div class="input-group">{input}<span class="input-group-btn">{button}</span></div> </div> ',
                'options'       => ['class' => 'form-control'],
                'buttonOptions' => ['class' => 'btn btn-default'],
                'multiple'      => false       // возможность выбора нескольких файлов
            ]); ?>
        </div>
    </div>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/modules/catalog/views/category/_view.php
<?php
use yii\helpers\Url;
?>
<tr>
    <td class="checkbox-item" style="width: 10px;" >
        <input type="checkbox" name="selection[]" value="<?=$model->id ?>">
    </td>
    <td  style="padding-left: <?= $level ? $level * 25 : 10 ?>px" class="sort-item">
        <i class="fa fa-arrows-alt"></i> <?=$model->title ?>
    </td>
    <td>
        <?=$model->statusDetail ?>
    </td>
    <td>
        <?=Yii::$app->formatter->asDatetime($model->updated_at) ?>
    </td>
    <td style="">
        <a class="btn btn-info btn-xs" href="<?=Url::to(['update', 'id' => $model->id]) ?>" title="Редагувати">
            <i class="fa fa-pencil"></i></a>
        <a class="btn btn-danger btn-xs" href="<?=Url::to(['delete', 'id' => $model->id]) ?>" title="Видалити" onclick="return confirm(&quot;Ви дійсно хочете видалити даний запис?&quot;)">
            <i class="fa fa-trash-o"></i>
        </a>
    </td>
</tr>

<?php foreach ($model->childrens as $item) :
    echo $this->render('_view', ['model' => $item, 'level' => $level + 1]) ?>
<?php endforeach; ?>

backend/modules/catalog/views/category/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\modules\core\models\NewsCategory */

$this->title = 'Создание';
$this->params['breadcrumbs'][] = ['label' => 'Категории', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="page-category-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/modules/catalog/views/category/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use backend\modules\catalog\models\CatalogCategory as CurrentModel;
use backend\widgets\SortActionWidget;

/* @var $this yii\web\View */
/* @var $searchModel backend\modules\core\models\PageCategorySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Категории';
$this->params['breadcrumbs'][] = $this->title;

\backend\widgets\SortActionWidget::widget(['className' => CurrentModel::className()]);
?>
<div class="page-category-index">
    <?= Html::a('<i class="fa fa-plus" aria-hidden="true"></i> Добавить', ['create'], ['class' => 'btn btn-success block right']) ?>

    <div class="pull-right">
        <?=\backend\widgets\GroupActionWidge::widget(['delete' => true, 'activate' => true, 'deactivate' => true, 'className' => CurrentModel::className()]) ?>
    </div>

    <?php Pjax::begin(['id' => 'content-list']) ?>

    <div id="myTabContent" class="tab-content">
        <div class="col-md-12 grid-view">
            <table class="table table-custom dataTable no-footer ">
                <thead>
                <tr>
                    <th></th>
                    <th>Назва</th>
                    <th>Статус</th>
                    <th>Редаговано</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($models as $model): ?>
                    <?=$this->render('_view', ['model' => $model, 'level' => 0]) ?>
                <?php endforeach; ?>
                </tbody
            </table>
        </div>
    </div>
    <?php Pjax::end() ?>
</div>

backend/modules/catalog/views/category/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\modules\core\models\NewsCategory */

$this->title = 'Редактирование: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Категории', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактирование';
?>
<div class="page-category-update">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

backend/modules/catalog/views/category/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\modules\core\models\NewsCategory */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Категории', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="page-category-view">
    <p>
        <?= Html::a('Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title:html',
            [
                'attribute' => 'image',
                'format' => ['image',['width'=>'70','height'=>'100']],
            ],
            'description',
            'text',
            [
                'attribute' => 'status',
                'value' => function($model) {
                    return $model->statusDetail;
                }
            ],
            'created_at:datetime',
            'updated_at:datetime',
            'alias',
        ],
    ]) ?>

</div>