backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use backend\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index', 'group', 'sort'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'group' => [
                'class' => 'backend\components\GroupAction',
            ],
            'sort' => [
                'class' => 'backend\components\SortAction',
            ],
        ];
    }


    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        $this->layout = 'login';

        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use backend\modules\catalog\models\CatalogCategory;
use backend\modules\core\models\Menu;
use backend\modules\core\models\Page;
use backend\modules\core\models\Setting;
use backend\modules\email_delivery\models\Subscriber;
use backend\modules\event\models\Event;
use backend\modules\news\models\News;
use backend\modules\section\models\SectionItem;
use backend\modules\slider\models\Slider;
use common\models\Lang;
use Yii;
use yii\base\InvalidParamException;
use yii\helpers\Url;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\web\Response;
use yii\widgets\ActiveForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    public $enableCsrfValidation = false;

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $lastNews = News::find()
            ->andWhere(['status' => News::STATUS_ACTIVE])
            ->orderBy(['id' => SORT_DESC])
            ->limit(3)
            ->joinWith('lang')
            ->all();

        $katalogSlider = CatalogCategory::find()->where(['alias' => 'catalog1'])->one();

        $katalog = SectionItem::getSectionByAlias('katalog-gotovykh-resheniy');
        $znaete = SectionItem::getSectionByAlias('ne-znaete-s-chego-nachat');
        $podrobnee = SectionItem::getSectionByAlias('podrobnee-pro-assotsiatsiyu');

        $model = new Subscriber();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', Yii::t('app', 'Спасибо за подписку на новости'));
            return $this->refresh();
        } else {
            return $this->render('index', [
                'lastNews' => $lastNews,
                'katalogSlider' => $katalogSlider,
                'katalog' => $katalog,
                'znaete' => $znaete,
                'podrobnee' => $podrobnee,
            ]);
        }
    }

    public function actionGetIndex()
    {
                $output = curl_init();	//подключаем курл
        curl_setopt($output, CURLOPT_URL, 'http://194.183.181.188:81/');	//отправляем адрес страницы
        curl_setopt($output, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($output, CURLOPT_HEADER, 0);
        $out = curl_exec($output);		//помещаем html-контент в строку
        curl_close($output);	//закрываем подключение
        echo $out;
//
//        $dom =  new \DOMDocument( "1.0", "ISO-8859-15" );	//создаем объект
//        $dom->loadHTML($out);	//загружаем контент
//
//        $xpath = new \DOMXpath($dom);
//        $articles = $xpath->query('//div[@class="col-md-8"]');
//
//        foreach($articles as $container) {
//            pr($articles->loadHTML());
//        }
    }

    public function actionContact()
    {
        $this->layout = 'contact';

        $page = Page::getPageByAlias('contact-page');

        return $this->render('contact', [
                'page' => $page,
        ]);

    }

    public function actionCalendar()
    {
        $model = new Event();

        $years = $model->getEventsItem();

        $days = Yii::$app->request->get('days') ?? 365;

        $timestamp = $days * 86400;

        if ($year = Yii::$app->request->get('year')){
            $events = $model->getEventByLetter($year, $timestamp);
        } else {
            $events = $model->getEventByLetter($year = end($years)['year'], $timestamp);
        }
//pr($events);
        $page = Page::getPageByAlias('kalendar-meropriyatiy');

        return $this->render('calendar', [
                'page' => $page,
                'years' => $years,
                'year' => $year,
                'last_year' => end($years)['year'],
                'events' => $events,
        ]);

    }

    public function actionSubscribeForm($rediractUrl)
    {

        $model = new Subscriber();


        if(Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
        else if ($model->load(Yii::$app->request->post()) && $model->save()) {

            Yii::$app->session->setFlash('success', 'Спасибо за подписку на новости');
            return $this->redirect($rediractUrl);
        }

    }

}

frontend/views/site/calendar.php
<?php
use yii\helpers\Url;
?>

<main class="page-template">
    <section class="block_header long">
        <div class="container-100">
            <div class="breadcrumbs">
                <a href="<?=Url::to(['/']) ?>">Главная</a>
                <span>/</span>
                <p><?= $page->title ?></p>
            </div>
        </div>
        <div class="container-100">
            <div class="text-information">
                <div class="title-block">
                    <h1><?= $page->title ?></h1>
                    <p><?= $page->description ?></p>
                </div>
            </div>
        </div>
    </section>
    <section class="template_4_calendar-nav">
        <div class="container-100">
            <?php if ($last_year == $year): ?>
                <div class="left-menu">
                    <a href="<?=Url::to(['/site/calendar/', 'days' => 365]) ?>" class="link active">Год</a>
                    <a href="<?=Url::to(['/site/calendar/', 'days' => 90]) ?>" class="link">Квартал</a>
                    <a href="<?=Url::to(['/site/calendar/', 'days' => 30]) ?>" class="link">Месяц</a>
                    <a href="<?=Url::to(['/site/calendar/', 'days' => 7]) ?>" class="link">Неделя</a>
                </div>
            <?php endif; ?>
            <div class="right-menu">
                <?php  foreach ($years as $item):?>
                    <a href="<?=Url::to(['/site/calendar/', 'year' => $item['year']]) ?>" class="link <?= $item['year'] == $year ? 'active' : '' ?>"><?= $item['year']; ?></a>
                <?php endforeach; ?>
            </div>
        </div>
    </section>
    <section class="template_4_services">
        <div class="bottom" style="background-image: url(<?= $page->image ?>)">
            <?php foreach ($events as $event): ?>
                <div class="box"  style="background-image: url(img/services.jpg)">
                    <h3><?= $event['title'] ?></h3>
                   <?= $event['short_description'] ?>
                    <a href="##" class="btn-orange">ПОДРОБНЕЕ</a>
                </div>
            <?php endforeach; ?>
        </div>
    </section>
</main>

frontend/views/site/contact.php
<?php
use common\models\Lang;
use frontend\widgets\BreadcrumbsWidget;

?>
<div class="wrapper">
    <div class="bread-crumbs">
        <?= BreadcrumbsWidget::widget() ?>
    </div>
    <?php if ($page->additional_title): ?>
        <h2 class="title"><?=$page->additional_title ?></h2>
    <?php endif; ?>
    <div class="contacts__list">
        <?= $page->text; ?>
    </div>
</div>
<?php if (Lang::getCurrent()->id == 1):?>
    <iframe   id="map" src="https://www.google.com/maps/d/embed?mid=1cGbvNQs7FbLle9heHYCN_ssz1wdkCxQJ" ></iframe>
<?php else:?>
    <iframe  id="map" src="https://www.google.com/maps/d/embed?mid=14WHR6e3ZbeD75ZIw18Iw1n9VvYi63Q2D&hl=en" ></iframe>
<?php endif;?>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php

use backend\modules\slider\models\Section;

use frontend\widgets\SubscribeWidget;

use yii\widgets\ActiveForm;

use yii\helpers\Html;

use yii\helpers\StringHelper;

use yii\helpers\Url;

use backend\modules\news\models\NewsCategory;





?>

<main class="page-home">

    <section class="page-home__main" style="background-image: url(/img/main.jpg)">

        <div class="row">

            <div class="left">

                <img src="/img/logo.png" alt="" class="logo">

            </div>

            <div class="right">

                <p>Фрейм с индексом</p>

            </div>

        </div>

        <div class="row">

            <div class="left">

                <?= $znaete->text ?>

                <a href="<?= $znaete->url ?>">К КАТАЛОГУ</a>

            </div>

            <div class="right">

                <?php if ($lastNews): ?>

                    <?php foreach ($lastNews as $item): ?>

                        <div class="box">

                            <?= Yii::$app->thumbnail->img($item->image, ['thumbnail' => ['width' => 480, 'height' => 270]], [

                                'alt' => $item->title,

                            ]) ?>

                            <h2><?= StringHelper::truncate(strip_tags($item->title), 70 )?></h2>

                            <p> <?= StringHelper::truncate(strip_tags($item->description), 250 )?></p>

                            <div class="bottom"><p><?=date("d.m.Y",strtotime($item->data_pub))?></p>

                                <?= Html::a(Yii::t('common', 'ПОДРОБНЕЕ'), ['/news/news/view', 'alias' => $item->alias]) ?>

                            </div>

                        </div>

                    <?php endforeach; ?>



                    <a href="<?= Url::to(['/news/news/all']) ?>" class="box all">

                        <h2><?= Yii::t('common', 'Все новости') ?></h2>

                    </a>

                <?php endif; ?>

            </div>

        </div>

    </section>



    <section class="page-home__ready" style="background-image: url(/img/bg_1.png)">

        <div class="container-100">

            <div class="left">

                <?= $katalog->text ?>

                <a href="<?= $katalog->url ?>" class="btn-orange">ПРОСМОТРЕТЬ ВЕСЬ КАТАЛОГ</a>

            </div>

            <div class="right">

                <div class="dragscroll draggable">
                    <p id="floatingmes">Нажмите и потяните</p>

                    <?php foreach ($katalogSlider->childrens as $item):?>

                        <div data-href="<?= $katalog->url ?>?category_id=<?= $item->id ?>" class="box">

                            <img src="<?= $item->image ?>" alt="">

                            <h3><?= $item->title ?></h3>

                        </div>

                    <?php endforeach; ?>

                </div>

            </div>

        </div>

    </section>

    <section class="page-home__assambl">

        <div class="container-100">

            <div class="content">

                <div class="left">

                    <?= $podrobnee->text ?>

                </div>

                <div class="right">

                    <div class="video">

                        <video poster="<?= $podrobnee->video_image ?>" autobuffer="" webkit-playsinline="false"  playsinline="true">

                            <source src="<?= $podrobnee->video ?>" type="video/mp4">

                        </video>

                        <div class="btn"></div>

                    </div>

                </div>

            </div>

            <div class="row-b">

                <div class="left">

                    <img src="<?= $podrobnee->image ?>" alt="">

                </div>

            </div>

        </div>

    </section>

    <?= SubscribeWidget::widget(['type' => 1]) ?>

</main>

<?php



//$this->registerJs("

//$.ajax({

//            url: '/site/get-index',

//            type: 'get',

//

//            success: function(html) {

//                $('.page-home__main .right').html($(html).find('.col-md-8').html());

//

//            }

//            });

//

//", \yii\web\View::POS_READY);

?>